on:
  pull_request:
    branches:
      - main

name: Geode CI

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Go Test
        run: |
          go test ./...
